package handoff

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/adrianmross/oci-identity-apps/internal/planner"
)

const SchemaVersion = "oci-idm.handoff.oci-context.v1"

type OCIContext struct {
	SchemaVersion string         `json:"schemaVersion"`
	TokenServices []TokenService `json:"tokenServices"`
	TokenCommands []TokenCommand `json:"tokenCommands"`
	Notes         []string       `json:"notes,omitempty"`
}

type TokenService struct {
	Name                   string `json:"name"`
	Type                   string `json:"type"`
	Flow                   string `json:"flow"`
	Issuer                 string `json:"issuer,omitempty"`
	AuthorizationEndpoint  string `json:"authorizationEndpoint,omitempty"`
	TokenEndpoint          string `json:"tokenEndpoint,omitempty"`
	ClientID               string `json:"clientId,omitempty"`
	ClientSecretEnv        string `json:"clientSecretEnv,omitempty"`
	Scope                  string `json:"scope,omitempty"`
	RedirectURL            string `json:"redirectUrl,omitempty"`
	PrivateKeyFileEnv      string `json:"privateKeyFileEnv,omitempty"`
	KeyID                  string `json:"keyId,omitempty"`
	JWTAudience            string `json:"jwtAudience,omitempty"`
	AssertionCommandEnv    string `json:"assertionCommandEnv,omitempty"`
	SubjectTokenCommandEnv string `json:"subjectTokenCommandEnv,omitempty"`
	SubjectTokenType       string `json:"subjectTokenType,omitempty"`
	RequestedTokenType     string `json:"requestedTokenType,omitempty"`
}

type TokenCommand struct {
	Key         string `json:"key"`
	Description string `json:"description"`
	Command     string `json:"command"`
}

func ForOCIContext(plan planner.Plan) OCIContext {
	h := OCIContext{
		SchemaVersion: SchemaVersion,
		Notes: []string{
			"Add token_services entries to oci-context config, or use the commands directly for one-off validation.",
			"Do not place generated client secrets, private keys, or assertion values directly in shared config.",
		},
	}
	for _, app := range plan.Apps {
		service, ok := tokenServiceForApp(plan, app)
		if !ok {
			continue
		}
		h.TokenServices = append(h.TokenServices, service)
		h.TokenCommands = append(h.TokenCommands, TokenCommand{
			Key:         string(app.Key) + "-" + app.Name,
			Description: app.Purpose,
			Command:     tokenCommand(service),
		})
	}
	return h
}

func JSON(value OCIContext) ([]byte, error) {
	data, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(data, '\n'), nil
}

func TokenServicesYAML(value OCIContext) string {
	var b strings.Builder
	b.WriteString("# oci-context token_services fragment generated by oci-idm.\n")
	b.WriteString("# Merge these entries into ~/.oci-context/config.yml or a project .oci-context/config.yml.\n")
	b.WriteString("token_services:\n")
	for _, service := range value.TokenServices {
		b.WriteString("  - name: " + yamlQuote(service.Name) + "\n")
		writeYAMLField(&b, "type", service.Type)
		writeYAMLField(&b, "flow", service.Flow)
		writeYAMLField(&b, "issuer", service.Issuer)
		writeYAMLField(&b, "authorization_endpoint", service.AuthorizationEndpoint)
		writeYAMLField(&b, "token_endpoint", service.TokenEndpoint)
		writeYAMLField(&b, "client_id", service.ClientID)
		writeYAMLField(&b, "client_secret_env", service.ClientSecretEnv)
		writeYAMLField(&b, "scope", service.Scope)
		writeYAMLField(&b, "redirect_url", service.RedirectURL)
		writeYAMLField(&b, "private_key_file_env", service.PrivateKeyFileEnv)
		writeYAMLField(&b, "key_id", service.KeyID)
		writeYAMLField(&b, "jwt_audience", service.JWTAudience)
		writeYAMLField(&b, "assertion_command_env", service.AssertionCommandEnv)
		writeYAMLField(&b, "subject_token_command_env", service.SubjectTokenCommandEnv)
		writeYAMLField(&b, "subject_token_type", service.SubjectTokenType)
		writeYAMLField(&b, "requested_token_type", service.RequestedTokenType)
	}
	return b.String()
}

func TokenCommandsScript(value OCIContext) string {
	var b strings.Builder
	b.WriteString("#!/usr/bin/env bash\nset -euo pipefail\n\n")
	b.WriteString("# Generated by oci-idm. Export any referenced *_SECRET, *_PRIVATE_KEY_FILE,\n")
	b.WriteString("# *_ASSERTION_COMMAND, or *_SUBJECT_TOKEN_COMMAND variables before running.\n\n")
	for _, command := range value.TokenCommands {
		b.WriteString("# " + command.Description + "\n")
		b.WriteString(command.Command + "\n\n")
	}
	return b.String()
}

func tokenServiceForApp(plan planner.Plan, app planner.AppPlan) (TokenService, bool) {
	endpoint := strings.TrimRight(plan.Target.Issuer, "/") + "/oauth2/v1/token"
	authorize := strings.TrimRight(plan.Target.Issuer, "/") + "/oauth2/v1/authorize"
	service := TokenService{
		Name:          tokenServiceName(plan, app),
		Type:          "oauth",
		Issuer:        plan.Target.Issuer,
		TokenEndpoint: endpoint,
		ClientID:      app.Name,
		Scope:         plan.Target.Scope,
	}
	switch app.Key {
	case planner.AppUser:
		service.Flow = "authorization-code"
		service.AuthorizationEndpoint = authorize
		service.RedirectURL = plan.Target.RedirectURL
	case planner.AppService:
		service.Flow = "client-credentials"
		service.ClientSecretEnv = envName(app.Name, "CLIENT_SECRET")
	case planner.AppJWTService:
		service.Flow = "jwt-client-credentials"
		service.PrivateKeyFileEnv = envName(app.Name, "PRIVATE_KEY_FILE")
		service.KeyID = certificateAlias(app)
		service.JWTAudience = "https://identity.oraclecloud.com/"
	case planner.AppJWTUser:
		service.Flow = "jwt-bearer"
		service.ClientSecretEnv = envName(app.Name, "CLIENT_SECRET")
		service.AssertionCommandEnv = envName(app.Name, "ASSERTION_COMMAND")
	case planner.AppWorkload:
		service.Flow = "token-exchange"
		service.ClientSecretEnv = envName(app.Name, "CLIENT_SECRET")
		service.SubjectTokenCommandEnv = envName(app.Name, "SUBJECT_TOKEN_COMMAND")
		service.SubjectTokenType = "urn:ietf:params:oauth:token-type:jwt"
		service.RequestedTokenType = "urn:ietf:params:oauth:token-type:access_token"
	default:
		return TokenService{}, false
	}
	return service, true
}

func tokenServiceName(plan planner.Plan, app planner.AppPlan) string {
	service := strings.TrimSpace(string(plan.Target.Service))
	if service == "" || service == string(planner.ServiceGeneric) {
		return app.Name
	}
	switch app.Key {
	case planner.AppUser:
		return service
	case planner.AppService:
		return service + "-service"
	case planner.AppJWTService:
		return service + "-jwt-service"
	case planner.AppJWTUser:
		return service + "-jwt-user"
	case planner.AppWorkload:
		return service + "-workload"
	default:
		return app.Name
	}
}

func tokenCommand(service TokenService) string {
	args := []string{
		"oci-context auth token",
		"--service " + shellQuote(service.Name),
		"--flow " + shellQuote(service.Flow),
	}
	if service.Issuer != "" {
		args = append(args, "--issuer "+shellQuote(service.Issuer))
	}
	if service.TokenEndpoint != "" {
		args = append(args, "--token-endpoint "+shellQuote(service.TokenEndpoint))
	}
	if service.ClientID != "" {
		args = append(args, "--client-id "+shellQuote(service.ClientID))
	}
	if service.ClientSecretEnv != "" {
		args = append(args, "--client-secret \"$"+service.ClientSecretEnv+"\"")
	}
	if service.Scope != "" {
		args = append(args, "--scope "+shellQuote(service.Scope))
	}
	if service.RedirectURL != "" {
		args = append(args, "--redirect-url "+shellQuote(service.RedirectURL))
	}
	if service.PrivateKeyFileEnv != "" {
		args = append(args, "--private-key-file \"$"+service.PrivateKeyFileEnv+"\"")
	}
	if service.KeyID != "" {
		args = append(args, "--key-id "+shellQuote(service.KeyID))
	}
	if service.JWTAudience != "" {
		args = append(args, "--jwt-audience "+shellQuote(service.JWTAudience))
	}
	if service.AssertionCommandEnv != "" {
		args = append(args, "--assertion-command \"$"+service.AssertionCommandEnv+"\"")
	}
	if service.SubjectTokenCommandEnv != "" {
		args = append(args, "--subject-token-command \"$"+service.SubjectTokenCommandEnv+"\"")
	}
	if service.SubjectTokenType != "" {
		args = append(args, "--subject-token-type "+shellQuote(service.SubjectTokenType))
	}
	if service.RequestedTokenType != "" {
		args = append(args, "--requested-token-type "+shellQuote(service.RequestedTokenType))
	}
	if service.Flow != "authorization-code" {
		args = append(args, "--no-login")
	}
	args = append(args, "--format raw")
	return strings.Join(args, " ") + " >/dev/null"
}

func certificateAlias(app planner.AppPlan) string {
	if len(app.OCICreatePayload.Certificates) > 0 && strings.TrimSpace(app.OCICreatePayload.Certificates[0].CertAlias) != "" {
		return app.OCICreatePayload.Certificates[0].CertAlias
	}
	return app.Name + "-cert"
}

func envName(parts ...string) string {
	joined := strings.Join(parts, "_")
	var b strings.Builder
	lastUnderscore := false
	for _, r := range joined {
		if (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
			lastUnderscore = false
			continue
		}
		if r >= 'a' && r <= 'z' {
			b.WriteRune(r - ('a' - 'A'))
			lastUnderscore = false
			continue
		}
		if !lastUnderscore {
			b.WriteByte('_')
			lastUnderscore = true
		}
	}
	return strings.Trim(b.String(), "_")
}

func writeYAMLField(b *strings.Builder, key string, value string) {
	if strings.TrimSpace(value) == "" {
		return
	}
	fmt.Fprintf(b, "    %s: %s\n", key, yamlQuote(value))
}

func yamlQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "''") + "'"
}

func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "'\"'\"'") + "'"
}
